MD013: false # Line length
MD024: false # Multiple headers with the same content
MD033: false # Allow inline HTML
MD036: false # Emphasis used instead of a header
MD045: false # Omit alternate text form image links
