MD004: false # Unordered list style
MD013: false # Line length
MD024: false # Multiple headers with the same content
MD029: false # Ordered list item prefix
MD033: false # Allow inline HTML
MD036: false # Emphasis used instead of a header
MD040: false # Fenced code blocks should have a language specified
MD045: false # Omit alternate text form image links
MD060: false # Table column style - table pipe is missing space
