# -------------------------------------------------------------------------
# Program: ci.yml
# Description: GitHub Actions CI — lint markdown, check for broken links (lychee), and run PSScriptAnalyzer
# Context: Learning Azure - repository continuous integration for docs (AZ-104) and scripts
# Author: Greg Tate
# -------------------------------------------------------------------------

# Workflow name
name: ci

# Workflow triggers: run on all branches, PRs, and weekday schedule for link checks
on:
  push: { branches: ["**"] }
  pull_request:
  schedule: [{ cron: "0 12 * * 1-5" }] # weekday link check

# CI jobs
jobs:

  # Markdown lint job (markdownlint) and inline link check (lychee)
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with: { globs: "**/*.md" }
      - uses: lycheeverse/lychee-action@v2
        with:
          args: "--no-progress --verbose **/*.md "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Dedicated link-check job using lychee (checks for broken links)
  link-check:
    name: Link check (lychee)
    runs-on: ubuntu-latest
    steps:
      # Checkout repository so lychee can scan files
      - uses: actions/checkout@v4

      # Run lychee to detect broken links in markdown files
      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # Recursively scan markdown files; verbose output helps debug broken links
          args: "--no-progress --verbose **/*.md"
        env:
          # Provide token to increase rate limits for external link checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # PowerShell static analysis job (PSScriptAnalyzer)
  powershell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PSScriptAnalyzer
        if: hashFiles('**/*.ps1') != ''
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
          Invoke-ScriptAnalyzer -Path . -Recurse -ReportSummary
