name: ci
on:
  push: { branches: ["**"] }
  pull_request:
  schedule: [{ cron: "0 12 * * 1-5" }] # weekday link check

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with: { globs: "**/*.md" }
      - uses: lycheeverse/lychee-action@v2
        with:
          args: "--no-progress --verbose **/*.md "
          failifempty: false

  # Dedicated link-check job using lychee (checks for broken links)
  link-check:
    name: Link check (lychee)
    runs-on: ubuntu-latest
    steps:
      # Checkout repository so lychee can scan files
      - uses: actions/checkout@v4

      # Run lychee to detect broken links in markdown files
      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # Recursively scan markdown files; verbose output helps debug broken links
          args: "--no-progress --verbose **/*.md"
          # Do not fail if no files are found (keeps job stable for repos without markdown)
          failifempty: false

  powershell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PSScriptAnalyzer
        if: hashFiles('**/*.ps1') != ''
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
          Invoke-ScriptAnalyzer -Path . -Recurse -ReportSummary
