# -------------------------------------------------------------------------
# Program: ci.yml
# Description: GitHub Actions CI — lint markdown, check for broken links (lychee), and run PSScriptAnalyzer
# Context: Learning Azure - repository continuous integration for docs (AZ-104) and scripts
# Author: Greg Tate
# -------------------------------------------------------------------------

# Workflow name
name: ci

# Workflow triggers: run on all branches, PRs, and weekday schedule for link checks
on:
  push: { branches: ["**"] }
  pull_request:
  schedule: [{ cron: "0 12 * * 1-5" }] # weekday link check

# CI jobs
jobs:

  # Markdown lint job (markdownlint only)
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with: { globs: "**/*.md" }

  # Dedicated link-check job using lychee (checks for broken links)
  link-check:
    name: Link check (lychee)
    runs-on: ubuntu-latest
    steps:
      # Checkout repository so lychee can scan files
      - uses: actions/checkout@v4

      # Run lychee to detect broken links in markdown files
      - name: Check links with lychee
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # Recursively scan markdown files; verbose output helps debug broken links
          args: "--no-progress --verbose **/*.md"
        env:
          # Provide token to increase rate limits for external link checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Send email notification only on failure
      - name: Send email notification on link check failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "❌ Broken links detected in ${{ github.repository }}"
          to: ${{ secrets.MAIL_TO }}
          from: GitHub Actions
          body: |
            Link check failed in repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}

            View details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Please review the failed links and update the documentation.

  # PowerShell static analysis job (PSScriptAnalyzer)
  powershell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PSScriptAnalyzer
        if: hashFiles('**/*.ps1') != ''
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
          Invoke-ScriptAnalyzer -Path . -Recurse -ReportSummary
